language: clojure
lein: 2.9.1
jdk:
  - openjdk11
install: lein i
cache:
  directories:
    - .graalvm
    - $HOME/.m2
script:
  - lein ancient
  - lein t
  - lein native-image
  # Smoke test for native image
  - echo "(ns foo.bar)" | target/native/imo-linux-amd64 -
