FROM openjdk:11

RUN apt-get update && apt-get install -y build-essential zlib1g-dev
RUN curl -o /usr/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/2.9.1/bin/lein \
  && chmod 755 /usr/bin/lein \
  && lein -version

RUN mkdir -p /work/scripts
COPY setup_graalvm.sh /work/scripts/setup_graalvm.sh
RUN /work/scripts/setup_graalvm.sh 11

WORKDIR /work
