name: Build
on: push
jobs:
  check-dependencies:
    name: Check outdated dependency versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: deps-${{ runner.os }}-${{ hashFiles('project.clj') }}
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.6
      - run: lein ancient
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: deps-${{ runner.os }}-${{ hashFiles('project.clj') }}
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.6
      - run: lein t
  build-native-image:
    name: Build native image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: deps-${{ runner.os }}-${{ hashFiles('project.clj') }}
      - name: Cache GraalVM
        uses: actions/cache@v2
        with:
          path: .graalvm
          key: graalvm-${{ runner.os }}-${{ hashFiles('graalvm.version') }}
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.6
      - run: |
          lein native-image
          echo "(ns smoke.test)" | target/native/imo-linux-amd64 -
